### PR TITLE
adding code coverage

### PR DESCRIPTION
**Pull request by ekryski**
It's not great on this repo

### CODE REVIEW

**Comment by ekryski** [comment]
It's breaking on Node < 4 because of jsdom. @daffl what do you want to do here?

Drop jsdom entirely? Roll back to an older version? Or just build for node 4, 6 and latest. Personally I'd rather stick to our LTS and try and just pull jsdom. It was noisy with greenkeeper and we're only using it in one spot.

**Comment by ekryski** [comment]
Actually it looks like feathers-socket-commons doesn't support node 0.10 and 0.12 so we may as well just drop those here as well.

The reason we didn't see that stuff is because we weren't running our tests against those versions on Travis.

**Comment by daffl** [comment]
Allright, I'm skipping the JSDom based jQuery tests now. We'll just add it to feathers-client.

**Comment by daffl** [comment]
Nevermind, you are right. Let's just remove the old Node version tests. We're still using Babel and don't plan any major changes here until the end of the year.

**Pull request merged**
