### PR TITLE
Typescript Definitions

### PR DESCRIPTION
**Pull request by AbraaoAlves**
### Summary
Fix [#381](https://github.com/feathersjs/feathers/issues/381)

### CODE REVIEW

**Comment by daffl** [comment]
I think someone mentioned the issue with `feathers-rest` before. Can you create an issue (with a suggested fix if possible) in both repos?

**Comment by myknbani** [comment]
I'll try editing the `.d.ts` files in `node_modules`.  Sadly I'm no expert in creating typescript definitions.

**Comment by daffl** [comment]
Probably by changing https://github.com/feathersjs/feathers-rest/blob/master/index.d.ts#L1 to something like:

```js
declare function rest(handler?: Function): Function;
```

**Comment by myknbani** [comment]
yes that's correct for `rest()`, 

and for "feathers-socketio", I'll just comment it here if you don't mind 😁...might create an issue or PR after I investigate further.

```
import 'socket.io';

type FeatherSocketCallback =
  (io: any) => void;

interface ServerOptions extends SocketIO.ServerOptions {
    wsEngine?: string; // <-- added this as well
}

type FeathersSockeOptions =
  ServerOptions |
  FeatherSocketCallback;

declare function e(
    options: FeathersSockeOptions,
    config?: FeathersSockeOptions
  ): () => void;

declare namespace e {}  // <-- it's a Typescript thing: 

export = e;
```

Exporting a function `foo` requires you declare a namespace `foo` as well, probably for `foo.extras`.
https://github.com/Microsoft/TypeScript/issues/6656#issuecomment-175780097

I also found out that a service instance doesn't have `before` and `after` methods, though I dunno how to do declaration merging for things inside a namespace.

Also, the typedefs for 'feathers-authentication` is for the pre-1.0.0 version.

**Comment by myknbani** [comment]
I managed to get my app to typecheck.  I'll try to gather/remember my tweaks and send PRs.

**Comment by daffl** [comment]
Cool thank you. Maybe we leave `wsEngine` out for now since there are a bunch more options available for Socket.io.

**Pull request merged**
