### PR TITLE
Correctly handling status codes with fetch

### LINKED ISSUE #4: Errors aren't returned correctly when using fetch
Status codes from the API need to be handled and errors thrown appropriately as fetch doesn't check error codes internally.

### PR DESCRIPTION
**Pull request by corymsmith**
Fixes #4 to properly throw errors

### CODE REVIEW

**Comment by daffl** [comment]
Is the tests at https://github.com/feathersjs/feathers-commons/blob/master/src/test/client.js#L76 missing something? I'm wondering why that passed before.

**Comment by corymsmith** [comment]
Yes it must be, I looked at the tests a bit and tried to set up some failing tests around it so I could make them pass with this fix and couldn't quite sort it so just tested manually :)

**Comment by daffl** [comment]
Do you have a breaking service/request combination?

**Comment by corymsmith** [comment]
I was doing a find that was throwing a 500 or 401 error

**Comment by ekryski** [comment]
Ya I was literally going to ask the same. The way the common tests are written in `feathers-commons` it's not easy to throw a 404 to test it. Gonna tinker with it a bit. It is kind of an important one to have a test around.

**Comment by daffl** [comment]
But it is throwing an error at https://github.com/feathersjs/feathers-rest/blob/master/test/client/server.js#L23 and verifying that the client resolves with that error at https://github.com/feathersjs/feathers-commons/blob/master/src/test/client.js#L76. That should at least send a 500 status code.

**Comment by ekryski** [comment]
I added a test for this and pushed it to master.

**Pull request merged**
