### PR TITLE
Return null for no-content responses with fetch

### LINKED ISSUE #83: Client fails to parse json response on 204 status using fetch
### Steps to reproduce
Call a service method which returns a `204` status with no body while using the `fetch` connection - `response.json()` then fails to parse the body and throws and error.

https://jsbin.com/wacosaneqo/edit?html,console

### Expected behavior
It should return a `null` response and throw no error

### Actual behavior
Throws `Error: Unexpected end of JSON input`

### System configuration
**Operating System**:
macOS Sierra

**Browser Version**:
Chrome 54

### PR DESCRIPTION
**Pull request by bedeoverend**
Checks if the response is 204 when using fetch and return `null` body. Fixes #83

### CODE REVIEW

**Comment by bedeoverend** [comment]
@daffl so this isn't ready to merge yet - what I've added in has broken quite a few tests, though I'm not quite sure why or what's going on - I don't think I'm familiar enough with the tests setup.

I'm also not really satisfied with the test setup i.e. without the 'fix' the tests fail saying `Expected {} === null`, rather than throwing the expected error as outlined in #83. But I don't think we can get around that until https://github.com/bitinn/node-fetch/issues/165 is resolved / reverted.

**Comment by daffl** [comment]
@bedeoverend I made a comment. I think you just need to add a `return`.

**Comment by bedeoverend** [comment]
Thanks @daffl - can't believe I missed that one. That's done the trick, looks all good now. Tried it out in a local project I'm working on that I discovered the bug initially in, and works well now.

**Comment by daffl** [comment]
Perfect, thank you! Released in v1.5.2. feathers-client will be updated once the tests pass.

**Comment by bedeoverend** [comment]
Sounds good. No worries - thanks for all the hard work!

**Pull request merged**
